#ifndef LOG_ISOLATOR_ENGINE_H
#define LOG_ISOLATOR_ENGINE_H

#include <string>
#include <vector>
#include <unordered_set>
#include <algorithm>

namespace dx3270 {

enum class FilterMode {
    Off,         // Standard Rendering without modifications
    Dimming,     // Reduces the opacity of extraneous noise to 25%
    Strict       // Strictly isolates only the relevant lines
};

enum class LineOwnership {
    Owned,       // Generated by the current user, their Jobs, the ASID, or the active pattern
    System,      // Critical system messages (ABEND, WTOR, console master)
    Foreign      // Noise generated by other users or shared controllers
};

class LogIsolatorEngine {
public:
    LogIsolatorEngine() = default;
    ~LogIsolatorEngine() = default;

    // User environment and dynamic pattern configuration
    void setCurrentUser(const std::string& userId);
    void setActiveASID(const std::string& asid);
    void addMonitoredJob(const std::string& jobIdOrName);
    void clearMonitoredJobs();
    void setFilterPattern(const std::string& pattern);

    const std::string& filterPattern() const { return m_activePattern; }

    // Operating mode
    void setMode(FilterMode mode) { m_mode = mode; }
    FilterMode mode() const { return m_mode; }

    // Automatic interception of events from the terminal data stream
    void inspectStreamForEvents(const std::string& textLine);

    // Line evaluation
    LineOwnership evaluateLine(const std::string& lineText) const;

private:
    std::string m_currentUser;
    std::string m_activeASID;
    std::string m_activePattern;
    std::unordered_set<std::string> m_monitoredJobs;
    FilterMode m_mode = FilterMode::Off;

    std::string toUpper(const std::string& str) const;
};

} // namespace dx3270

#endif // LOG_ISOLATOR_ENGINE_H